version: "3"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=status
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always

  cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    image: cachet:2.4
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PREFIX=${DB_PREFIX}
      - APP_KEY=${APP_KEY}
      - APP_LOG=${APP_LOG}
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG}
      - DEBUG=${DEBUG}
    depends_on:
      - postgres
    restart: on-failure

  zabbix-cachet:
      build:
         context: ./zabbix
         dockerfile: Dockerfile
      image: zabbix-cachet
      volumes:
        - ./zabbix/config.yml:/config.yml
